spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aviaservice?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: ${USER_DB}
    password: ${PASS_DB}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080