spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aviaservice?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: ${USER_DB}
    password: ${PASS_DB}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mail.ru
    port: 587
    username: ${USER_MAIL}
    password: ${PASS_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8080